version: 2
jobs:
  build:
    working_directory: ~/pauling
    docker:
      - image: python:3.6.0
        environment:
          FLASK_CONFIG: testing
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
          SECRET_KEY: 'secretkey'
          CLOUDINARY_URL: ''
          CLOUDINARY_BASE_URL: 'https://res.cloudinary.com/tailordev'
      - image: postgres:9.6-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "api/requirements-dev.txt" }}
      - run:
          name: make bootstrap
          working_directory: ~/pauling/api
          command: make bootstrap
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "api/requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          name: make test-ci
          working_directory: ~/pauling/api
          command: make test-ci
      - store_test_results:
          path: /reports
      - run:
          name: setup Heroku deployment
          command: bash .circleci/heroku-setup.sh
      - add_ssh_keys:
          fingerprints:
            - "SHA256:T2bQRNgGRXJm0ko8chtHswXMTP6ObmDBhVXuD34qMV4"
      - deploy:
          name: deploy master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make deploy-api
              heroku run FLASK_APP=server.py flask db upgrade
            fi
