version: '3'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: pauling
      POSTGRES_USER: pauling
      POSTGRES_PASSWORD: paulingpassword
    ports:
      - 127.0.0.1:15432:5432
