version: '3'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: pauling
      POSTGRES_USER: pauling
      POSTGRES_PASSWORD: paulingpassword
    ports:
      - 127.0.0.1:15432:5432

  mailer:
    image: tophfr/mailcatcher:0.6.5
    ports:
      - 127.0.0.1:15080:80
      - 127.0.0.1:15025:25
